### PR TITLE
adding public_key_read_access

### PR DESCRIPTION
**Pull request by jeremymv2**
Issue: Users are getting 403 errors on the `public_key_read_access` acl/group since it is not using the 'pivotal' user.

```
knife ec backup ./lm-backup -c ./knife.rb --webui-key c:\path\to\files\webui_priv.pem --concurrency 1

ERROR: /acls/groups/public_key_read_access.json failed to read: HTTP error reading: 403 "Forbidden"

10.172.85.71 - - [25/Jul/2016:19:32:56 -0400]  "GET /organizations/lm/groups/public_key_read_access/_acl HTTP/1.1" 403 "0.014" 37 "-" "Chef Knife/12.10.24 (ruby-2.1.8-p440; ohai-8.16.0; i386-mingw32; +https://chef.io)" "127.0.0.1:8000" "403" "0.014" "12.10.24" "algorithm=sha1;version=1.1;" "n0059475" "2016-07-25T23:32:55Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 1082
10.172.85.71 - - [25/Jul/2016:19:35:20 -0400]  "GET /organizations/training/groups/public_key_read_access/_acl HTTP/1.1" 403 "0.013" 37 "-" "Chef Knife/12.10.24 (ruby-2.1.8-p440; ohai-8.16.0; i386-mingw32; +https://chef.io)" "127.0.0.1:8000" "403" "0.013" "12.10.24" "algorithm=sha1;version=1.1;" "training" "2016-07-25T23:35:19Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 1088
10.172.85.71 - - [25/Jul/2016:19:35:57 -0400]  "GET /organizations/kbeaud/groups/public_key_read_access/_acl HTTP/1.1" 403 "0.015" 37 "-" "Chef Knife/12.10.24 (ruby-2.1.8-p440; ohai-8.16.0; i386-mingw32; +https://chef.io)" "127.0.0.1:8000" "403" "0.015" "12.10.24" "algorithm=sha1;version=1.1;" "n0218804" "2016-07-25T23:35:56Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 1086
```

`public_key_read_access` is a special group added to Chef Server 12.5 - it has similar ACL restrictions as the `billing-admins` group.  This PR takes this into account and treats them the same - using the `pivotal` user to handle reads/changes to those objects.

### CODE REVIEW

**Comment by jeremymv2** [comment]
After the changes you can see the `pivotal` user is utilized.

```192.168.200.1 - - [26/Jul/2016:18:15:54 +0000]  "GET /organizations/brewinc/groups/public_key_read_access/_acl HTTP/1.1" 200 "0.021" 113 "-" "Chef Knife/12.11.18 (ruby-2.1.8-p440; ohai-8.16.0; x86_64-darwin13.0; +https://chef.io)" "127.0.0.1:8000" "200" "0.021" "12.11.18" "algorithm=sha1;version=1.1;" "pivotal" "2016-07-26T18:15:54Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 1094```

**Comment by stevendanna** [comment]
Looks reasonable to me.

**Comment by jsmartt** [comment]
@jaymzh , it broke our restore also. Did you find a good way to work around those issues?

**Comment by stevendanna** [comment]
@jsmartt To make sure I understand, I am assuming your restore was taken from a version of chef-server that didn't have the public_key_read_access_group?

**Comment by jsmartt** [comment]
Doh! Must have scp'd the backup from when my server was 12.4.1 (did a backup before and after upgrading). Looks like my backup from 12.10.0 does include that file. Thanks for the quick response!

**Comment by poliva83** [comment]
@stevendanna @jsmartt This does bring up an interesting point. Does this change break users with chef-server version < 12.5. If it does then in my opinion it should be captured in the README.md. Basically say the minimum `chef-server-core` package version that the latest `knife-ec-backup` gem is compatible with. `knife-ec-backup` gem is one of the embedded gems in chef-server-core package but if someone tried to upgrade the gem on their older chef 12 server they will likely have problems.

**Comment by stevendanna** [comment]
@poliva83 It does appear to break users of older cher-server as well as break cross-version restores which I think we should still support where possible.

**Comment by stevendanna** [comment]
@jsmartt @jaymzh @poliva83 I made this issue here: https://github.com/chef/knife-ec-backup/issues/84  I can't say when I'll be able to look into it, but we can at least centralize the discussion there.

**Pull request merged**
