### PR TITLE
add acl matching for subpaths and leafs

### PR DESCRIPTION
**Pull request by jeremymv2**
This PR addresses two major items:

- Allows for backups to find and copy org-level acl subpaths and their children.

For org-level acl subpath objects, only `/acls/groups/*.json` and `/acls/organization.json` were being copied during a backup operation.

Now these additional acl leaf objects are captured and saved as well:
```
/acls/clients/*
/acls/containers/*
/acls/environments/*
/acls/nodes/*
```

- Removes redundancy in handling groups and groups acls.

The following pre-existing snippet already decides if using `pivotal` or an Org admin is appropriate

```
Chef::Config.node_name = if config[:skip_version]
                                      org_admin
                                    else
                                      server.supports_defaulting_to_pivotal? ? 'pivotal' : org_admin
                                    end
```

The lines explicitly handling the `/acls/groups/*` and `/groups/*` as `pivotal` that were removed in this PR are then uneeded.  The lines existed due to restrictive permissions on the objects requiring to be copied as `pivotal` for Server versions 12.5.x.  Whereas for Server 11.x, an Org admin is preferred. 
Now the objects are only copied once, if they exist, using the appropriate node_name.

### CODE REVIEW

**Comment by stevendanna** [comment]
Hrm.  I'm not sure this is correct.  Namely, I /think/ this will fail in cases where the chosen `org_admin` isn't a member of the `billing_admins` group.  The billing-admin group is only readable by `pivotal` and members of the `billing_admin` groups.  There is no guaranteed overlap between the membership of the billing_admin group and the admin group.

**Comment by jeremymv2** [comment]
"The billing-admin group is only readable by pivotal and members of the billing_admin groups. "

If I understand everything correctly, then:

-  Server 12.x is fine with the code as-is since it will default to `pivotal` via `server.supports_defaulting_to_pivotal?` Unless the user specified `--skip-version-check` (what use-case is that option trying to account for?)
-  For Server 11.x we are relying on `org_admin` to return a user that may or may not also be a member of `billing_admins`

Thus I think the failure scenario potentially exists no matter what for 11.x?

If that's the case, then I wonder if we should just default to `pivotal` in ALL cases.

**Comment by jeremiahsnapp** [comment]
Hey @jeremymv2 nice work! This PR fixes the problem. All the acls are getting backed up and now the acls/organizations.json is getting backed up again too.

By the way, all chef servers have had a pivotal user so 11.x should be fine with regards to the pivotal user.

```
root@chef:/# diff --brief -r broken-backup fixed-backup
Only in fixed-backup/organizations/automate/acls: clients
Only in fixed-backup/organizations/automate/acls: containers
Only in fixed-backup/organizations/automate/acls: cookbooks
Only in fixed-backup/organizations/automate/acls: environments
Only in fixed-backup/organizations/automate/acls: nodes
Only in fixed-backup/organizations/demo/acls: clients
Only in fixed-backup/organizations/demo/acls: containers
Only in fixed-backup/organizations/demo/acls: environments
```

**Comment by stevendanna** [comment]
> By the way, all chef servers have had a pivotal user so 11.x should be fine with regards to the pivotal user.


The problem isn't whether pivotal exists, but whether pivotal passes the is_user_in_org check.  I think the history of that is a bit complicated.  I would need to do some git archeology to know the exact breakdown.

**Comment by stevendanna** [comment]
Do we know when the bug wrt acls not being copied was introduced, as I definitly have backups with acls in them from older versions of knife-ec-backup?

**Comment by jeremymv2** [comment]
@stevendanna I think the missing acls issue was introduced sometime between 2.0.6 and 2.0.7, around when we added support for `public_key_read_access` and implemented `normalize_path_name`.

Namely, it's these that are now missing:
```
/acls/clients/*dddddddd
/acls/containers/*
/acls/environments/*
/acls/nodes/*
```

It appears to have something to do with `.json` extension on acl objects.  I added some comments in this PR that attempt to explain this:

```
          # The top level acl object names end with .json extension
          # Therefore we can use Chef::ChefFS::FilePattern matching for items
          # such as /acls/organizations.json
          #
          # 2nd level leaf /acl/*/* objects as well as /groups/* objects do not end with .json
          # therefore we use normalize_path_name to add the .json extension
          # for example: /acls/environments/_default
```

To address your concerns of pivotal vs org_admin, I put back the block specifically downloading the billing-admins, public_key_read_access ACL and groups as pivotal and re-added them to the exclude list for the remainder of the org objects.

I've verified the missing objects are again being backed up:
```
Downloading Users
Downloading organization object for brewinc from https://chef-server.test/organizations/brewinc
Created /acls
Created /acls/groups
Created /acls/groups/billing-admins.json
Created /groups
Created /groups/billing-admins.json
Created /acls/groups/public_key_read_access.json
Created /groups/public_key_read_access.json
Created /groups/admins.json
Created /clients
Created /clients/brewinc-validator.json
Created /containers
Created /containers/groups.json
Created /containers/cookbooks.json
Created /containers/clients.json
Created /containers/cookbook_artifacts.json
Created /containers/nodes.json
Created /containers/containers.json
Created /containers/data.json
Created /containers/policies.json
Created /containers/environments.json
Created /containers/policy_groups.json
Created /containers/roles.json
Created /containers/sandboxes.json
Created /cookbook_artifacts
Created /cookbooks
Created /data_bags
Created /environments
Created /environments/_default.json
Created /invitations.json
Created /members.json
Created /nodes
Created /nodes/foo.json
Created /policies
Created /policy_groups
Created /roles
Created /acls/organization.json
Created /acls/clients
Created /acls/clients/brewinc-validator.json
Created /acls/containers
Created /acls/containers/clients.json
Created /acls/containers/containers.json
Created /acls/containers/cookbook_artifacts.json
Created /acls/containers/cookbooks.json
Created /acls/containers/data.json
Created /acls/containers/environments.json
Created /acls/containers/groups.json
Created /acls/containers/nodes.json
Created /acls/containers/policies.json
Created /acls/containers/policy_groups.json
Created /acls/containers/roles.json
Created /acls/containers/sandboxes.json
Created /acls/environments
Created /acls/environments/_default.json
Created /acls/groups/000000000000a6b40724afbc2dda70c5.json
Created /acls/groups/000000000000e5d7de524dbe2c321bf7.json
Created /acls/groups/admins.json
Created /acls/groups/clients.json
Created /acls/groups/users.json
Created /acls/nodes
Created /acls/nodes/foo.json
Created /groups/000000000000a6b40724afbc2dda70c5.json
Created /groups/000000000000e5d7de524dbe2c321bf7.json
Created /groups/clients.json
Created /groups/users.json
```

**Comment by itmustbejj** [comment]
👍

**Pull request merged**
