### PR TITLE
VERSION metadata

### PR DESCRIPTION
**Pull request by jeremymv2**
🚧 this is to handle #107 🚧 

Signed-off-by: Jeremy J. Miller <jm@chef.io>

### CODE REVIEW

**Comment by jeremymv2** [comment]
@stevendanna I'm moving this forward 😃

**Comment by stevendanna** [comment]
Awesome, thanks

**Comment by jeremymv2** [comment]
removing 🚧

ready for review

**Comment by afiune** [comment]
Maybe a little bit of context of what this change is for? 😄  - Otherwise I feel I'm approving some code that kinda doesn't something but not sure what is it for. (maybe I'm lacking context so forgive me if that is the case 😅 )

**Comment by stevendanna** [comment]
The new class looks good but I'm not seeing where we use it to actually store the new info in the backup.

**Pull request closed without merging**
